version: "3.9"
services:
  build:
    build:
      context: ./
      dockerfile: ./docker/build/Dockerfile
      network: host
    container_name: build
    profiles:
      - build
    volumes:
      - ./:/pg_kalman
    working_dir: /pg_kalman
    command: bash -c "make"
    network_mode: "host"
  demo:
    build:
      context: ./
      dockerfile: ./docker/demo/Dockerfile
    container_name: pg_kalman
    restart: always
    profiles:
      - demo
    volumes:
      - ./:/pg_kalman
      - ./sql/demo.sql:/docker-entrypoint-initdb.d/1.sql
      - data:/var/lib/postgresql/data
    working_dir: /pg_kalman
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - ./.env
  test:
    build:
      context: ./
      dockerfile: ./docker/test/Dockerfile
      network: host
    container_name: test
    profiles:
      - test
    volumes:
      - ./:/pg_kalman
    working_dir: /pg_kalman
    env_file:
      - ./.env
    network_mode: "host"
volumes:
  data:
